### ISSUE TITLE
Image Captioning training error

### ISSUE THREAD

**Issue by MichaelSunEngineer** [uber/ludwig#112]
raise ValueError("Cannot convert an unknown Dimension to a Tensor: %s" % d)
ValueError: Cannot convert an unknown Dimension to a Tensor: ?

wo can help me ……

**Comment by w4nderlust** [comment]
Your have to provide all the information needed to debug: code, data, model definition, os version, python version and installed packages, otherwise we are unable to help you.

**Comment by MichaelSunEngineer** [comment]
@w4nderlust ok,thank you.
pip list
absl-py (0.7.0)
astor (0.7.1)
certifi (2018.11.29)
chardet (3.0.4)
cloudpickle (0.8.0)
cycler (0.10.0)
cymem (2.0.2)
Cython (0.29.5)
cytoolz (0.9.0.1)
dask (1.1.1)
decorator (4.3.2)
dill (0.2.9)
en-core-web-sm (2.0.0)
gast (0.2.2)
grpcio (1.18.0)
h5py (2.9.0)
idna (2.8)
Keras-Applications (1.0.7)
Keras-Preprocessing (1.0.9)
kiwisolver (1.0.1)
ludwig (0.1.0)
Markdown (3.0.1)
matplotlib (3.0.2)
msgpack (0.5.6)
msgpack-numpy (0.4.3.2)
murmurhash (1.0.1)
networkx (2.2)
numpy (1.16.1)
pandas (0.24.1)
Pillow (5.4.1)
pip (9.0.1)
plac (0.9.6)
preshed (2.0.1)
protobuf (3.6.1)
pyparsing (2.3.1)
python-dateutil (2.8.0)
pytz (2018.9)
PyWavelets (1.0.1)
PyYAML (3.13)
regex (2018.1.10)
requests (2.21.0)
scikit-image (0.14.2)
scikit-learn (0.20.2)
scipy (1.2.1)
seaborn (0.9.0)
setuptools (36.4.0)
six (1.12.0)
spacy (2.0.18)
tabulate (0.8.3)
tensorboard (1.12.2)
tensorflow (1.12.0)
termcolor (1.1.0)
thinc (6.12.1)
toolz (0.9.0)
tqdm (4.31.1)
ujson (1.35)
urllib3 (1.24.1)
Werkzeug (0.14.1)
wheel (0.29.0)
wrapt (1.10.11)


model_definition.yaml:
input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn
        resize_image: true
        height: 60
        width: 200
output_features:
    -
        name: caption
        type: sequence
        decoder: generator
        cell_type: lstm
training:
  epochs: 10


labels.csv:
image_path | caption
imagent/-14.7_0026912.jpg | -14.7
imagent/85.35_0011039.jpg | 85.35

and I use class classification function is success and I images are 200*60

error:
Traceback (most recent call last):
  File "/home/czc/anaconda3/envs/ludwig-py36/bin/ludwig", line 11, in <module>
    sys.exit(main())
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/cli.py", line 67, in experiment
    experiment.cli(sys.argv[2:])
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/experiment.py", line 548, in cli
    experiment(**vars(args))
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/experiment.py", line 258, in experiment
    debug=debug
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/train.py", line 368, in train
    debug=debug
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/models/model.py", line 110, in __init__
    **kwargs
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/models/model.py", line 184, in __build
    is_training=self.is_training
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/models/outputs.py", line 43, in build_outputs
    **kwargs
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/models/outputs.py", line 93, in build_single_output
    **kwargs
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/features/base_feature.py", line 314, in concat_dependencies_and_build_output
    **kwargs
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/features/sequence_feature.py", line 250, in build_output
    kwarg=kwargs
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/features/sequence_feature.py", line 320, in build_sequence_output
    eval_loss
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/features/sequence_feature.py", line 445, in sequence_measures
    self.name
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/models/modules/measure_modules.py", line 73, in masked_accuracy
    maxlen=correct_predictions.shape[1], dtype=tf.int32)
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2504, in sequence_mask
    maxlen = ops.convert_to_tensor(maxlen)
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 282, in _dimension_tensor_conversion_function
    raise ValueError("Cannot convert an unknown Dimension to a Tensor: %s" % d)
ValueError: Cannot convert an unknown Dimension to a Tensor: ?

**Comment by MichaelSunEngineer** [comment]
@w4nderlust  in file ludwig/models/modules/measure_modules.py  line 73  I change the maxlen=32, it work. But what is maxlen?

**Comment by MichaelSunEngineer** [comment]
@w4nderlust I change the maxlen=1, it really works ,can you tell me why?

**Comment by w4nderlust** [comment]
It looks like your output is a numeric value, why don't you use `type: numeric` instead?

**Comment by MichaelSunEngineer** [comment]
@ thanks i will try.  And I want to predict a image now by a .py flie. But fail ,this is my code

from ludwig import LudwigModel


model_path = './results/experiment_run_4/model'
model = LudwigModel.load(model_path)

dataframe = './tt/5.jpg'

dic = {'image_path': ['./tt/5.jpg'] }
predictions = model.predict(
    data_df=None,
    data_csv=None,
    data_dict=dic,
    return_type= 'pandas.core.frame.DataFrame',
    batch_size = 128,
    gpus = None,
    gpu_fraction = 1,
    logging_level = 40
)
print(predictions)
model.close()


can you help me please

**Comment by w4nderlust** [comment]
You have to tell me what error you got, how can I help you otherwise? :)

**Comment by MichaelSunEngineer** [comment]
@w4nderlust 
Traceback (most recent call last):
  File "predict.py", line 11, in <module>
    data_csv=csv_file
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/api.py", line 911, in predict
    logging_level=logging_level,
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/api.py", line 779, in _predict
    self.model_definition['preprocessing']
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 165, in build_data
    preprocessing_parameters
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/features/image_feature.py", line 57, in add_feature_data
    csv_path = os.path.dirname(os.path.abspath(dataset_df.csv))
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'csv'

**Comment by w4nderlust** [comment]
I pushed a fix, please install from the version of ludwig in master, retry and confirm that the fix solved your issue.

**Comment by MichaelSunEngineer** [comment]
I run the pip uninstall ludwig and pip install ludwig again, but the problem still exists.
Traceback (most recent call last):
  File "predict.py", line 33, in <module>
    logging_level = 40
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/api.py", line 906, in predict
    logging_level=logging_level,
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/api.py", line 774, in _predict
    self.model_definition['preprocessing']
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 165, in build_data
    preprocessing_parameters
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/ludwig/features/image_feature.py", line 57, in add_feature_data
    csv_path = os.path.dirname(os.path.abspath(dataset_df.csv))
  File "/home/czc/anaconda3/envs/ludwig-py36/lib/python3.6/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'csv'

**Comment by w4nderlust** [comment]
I said install from master, not reinstall from Pypi.
```
pip install git+https://github.com/uber/ludwig.git@master
```

**Comment by MichaelSunEngineer** [comment]
@w4nderlust 

Thank you very much for your help. It works, but changes different pictures, and the predictions are the same...

**Comment by w4nderlust** [comment]
Not sure what does that mean.

**Comment by MichaelSunEngineer** [comment]
@w4nderlust 

Anyway, thank you for your help, and I'm honored to offer some suggestions for such an excellent open source project. Thank you again.

**Comment by w4nderlust** [comment]
Sure, you're welcome :)
But again, try to explain what do you mean with "It works, but changes different pictures, and the predictions are the same..." because I don't get it, once I understand I can help you further.

**Comment by MichaelSunEngineer** [comment]
@w4nderlust 

It's the input of two different pictures, and the result is the same.
imageA==>-120.7
iamgeB==>-120.7
………===>-120.7

**Comment by w4nderlust** [comment]
Well maybe the images are similar. Anyhow you should use a numeric ouput, not a sequential one.
Closing the issue as this doesn't seem an error, but something that has to do with the dataset and the type of feature you are using. Cheers.

**Comment by MichaelSunEngineer** [comment]
@w4nderlust Thanks!

**Comment by MichaelSunEngineer** [comment]
@w4nderlust 
If I want to recognize the text in the picture, how should I set it?

**Comment by w4nderlust** [comment]
If you want to recognize the text, then use text output and decide if you want it at the word level of the character level.
