### ISSUE TITLE
UnicodeDecodeError when loading pretrained GloVe embeddings

### ISSUE THREAD

**Issue by vitojph** [uber/ludwig#336]
Hi all, 

I'd like to use GloVe vectors as pretrained embeddings when training a text classifier. I downloaded the [glove.840B.300d.zip vectors](http://nlp.stanford.edu/data/glove.840B.300d.zip), unzipped them, and specified in my model definition file the following lines:

```
input_features:
    -
        name: text
        type: text
        encoder: rnn
        cell_type: lstm_cudnn
        pretrained_embeddings: /home/victor/data/glove.840B.300d.txt
```

This is the error I get as soon as I launch the training:

```
embeddings = load_glove(embeddings_path)
  File "/home/victor/ludwig/lib/python3.6/site-packages/ludwig/utils/data_utils.py", line 178, in load_glove
    for line in f:
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1387: ordinal not in range(128)
```

All my files are encoded in UTF-8. I'm using Debian stable (Stretch), Python 3.6.8, ludwig 0.1.2 and TF 1.13.1.

Any ideas? Thanks in advance,

**Comment by w4nderlust** [comment]
Just pushed a quick fix that should solve the problem. Please install Ludwig from the latest commit on master with `pip install git+https://github.com/uber/ludwig.git` and let me know if the problem is solved.

**Comment by vitojph** [comment]
Hi, 

Great, thanks for the fix! It works now!

However, I just found out that some GloVe files don't have a regular format. For instance, `glove.840B.300d.zip` is supposed to contain 301-item lines (the token and its 300 weights) but some lines do contain more than one `str` tokens. As a consequence, when trying to convert some of these unexpected strings into floats in [this line](https://github.com/uber/ludwig/blob/c49dcfda4eeaea52bf0ee484970c54303d29bd64/ludwig/utils/data_utils.py#L182), it raises an exception.

Maybe we can safely ignore those files containing lines not matching the expected embedding size. 

Thanks again!

**Comment by w4nderlust** [comment]
@vitojph  could you please post here some examples line that raise exceptions so that I can figure out how to account for them?

**Comment by vitojph** [comment]
hi @w4nderlust,

When loading ie. [Common Crawl (840B tokens, 2.2M vocab, cased, 300d vectors, 2.03 GB download): glove.840B.300d.zip](http://nlp.stanford.edu/data/glove.840B.300d.zip), some lines seems to be ill-formed.

**Comment by w4nderlust** [comment]
I see. Thanks for inspecting this. I will do 2 things: 1) reproduce your result and try to figure out if those are actually malformed lines or if there are weird utf-8 characters that the split function doesn't recognize (or uses for splitting), 2) add more checks, discarding lines that are malformed. Stay tuned

**Comment by w4nderlust** [comment]
So it turned out there are some weird utf-8 space characters in that file. The reason is likely that in the glove c code they split using only the ASCII space.
I initially implemented a solution that was dealing with it by joining all the elements in the split that were not part of the embeddings, but that was slow and useless because those characters would not be present in tokens in Ludwig because of how Ludwig's tokenizers work.
So in the end I ended up just skipping those "malformed" lines, printing a warning.
@vitojph please let me know if now everything works as expected.

**Comment by abc1610** [comment]
@w4nderlust I am trying to load embeddings for my text input features but as soon as I start to train the model i get the following error:
``` UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2438: character maps to <undefined> ```

I already tried the it again by installing from ```pip install git+https://github.com/uber/ludwig.git``` but it still doesn't work. 

The commoncrawl embeddings file is from https://nlp.stanford.edu/projects/glove/

**Comment by w4nderlust** [comment]
@abc1110 use the code from master: `pip uninstall ludwig & pip install git+http://github.com/uber/ludwig.git`
The issue has been solved in master, i was able to load all the pretrained GloVe embeddings files.

**Comment by abc1110** [comment]
@w4nderlust I have tried that solution, but I am using the programmatic API where this issue persists..

**Comment by w4nderlust** [comment]
@abc1110 the command line and API use exactly the same code. Please make sure you are running the updated code. If you are, and still get an error, please make a reproducible example, because I tested wit all those retrained embeddings files and they all work.
