### ISSUE TITLE
Visualization (visualize.learning_curves) raises ValueError

### ISSUE THREAD

**Issue by lin4you** [uber/ludwig#500]
**Describe the bug**
If I'm trying to use the visualize.learning_curves function I'm always getting the ValueError: x and y must have same first dimension, but have shapes (20,) and (0,). This is also true if the ludwig cli is used as shown in the notebook in the last code block (I know, that it wont output plots, but it gives the same error).

**To Reproduce**
1. Go to https://colab.research.google.com/drive/1Eb0WoJzH_lJx4dG10ZOa3MT_Z1hu_bPK
2. Scroll down to last 3 code blocks 

**Expected behavior**
One should see two plots (accuracy and loss)

**Environment (please complete the following information):**
 - OS: Google Colab
- Python version: 3.6
- Ludwig version: master (see first block in notebook)

**Comment by w4nderlust** [comment]
I pushed a commit that fixes the issue. Can you please install Ludwig prom master `pip install git+http://github.com/uber/ludwig.git` and confirm the problem is fixed?

**Comment by lin4you** [comment]
I just tested the fix and I'm sorry to say, that I'm still getting this error. Even if I'm installing it via (pip install git+http://github.com/uber/ludwig.git). So the error still occurs in the notebook that I linked in the issue.
Hopefully I'm doing something wrong here.
Nevertheless, I am pleased that the issue has been dealt with so quickly.

**Comment by w4nderlust** [comment]
Can you pleasepast hereyou train_statistics.json file please?

On Thu, 22 Aug 2019 at 23:55, lin4you <notifications@github.com> wrote:

> I just tested the fix and I'm sorry to say, that I'm still getting this
> error. Even if I'm installing it via (pip install git+
> http://github.com/uber/ludwig.git
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig.git&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=oWkXX2kkKDDPZYBRp_yBLpMUsw3ViZa59nuS4k-k8uo&s=tIXvHumEKdoUTy3duZpKnDbNzaJvIFCxuDX8WqB_MTA&e=>).
> So the error still occurs in the notebook that I linked in the issue.
> Hopefully I'm doing something wrong here.
> Nevertheless, I am pleased that the issue has been dealt with so quickly.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_issues_500-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAACVISE5XZ343Y4XPJDWCTTQF6CVTA5CNFSM4IOD6K22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD47JWPA-23issuecomment-2D524196668&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=oWkXX2kkKDDPZYBRp_yBLpMUsw3ViZa59nuS4k-k8uo&s=ELnf-euoovpBpCyImmiQKz1fKPTo-rWvHGEj5U4xNvs&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACVISAOPLI5MHAULZL6623QF6CVTANCNFSM4IOD6K2Q&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=oWkXX2kkKDDPZYBRp_yBLpMUsw3ViZa59nuS4k-k8uo&s=j_YwAATuzYHRdR9qbWw2-VfdM5fkLvEbqYzIHp6Ajik&e=>
> .
>
-- 
----
Piero Molino
Sr Research Scientist
UBER AI Labs

**Comment by lin4you** [comment]
That's the training_statistics.json that I'm getting from the notebook mnist example that I added to this issue:

```json
{
    "test": {
        "combined": {
            "accuracy": [
                0.278,
                0.4152,
                0.4617,
                0.4871,
                0.4442,
                0.5866,
                0.5665,
                0.5625,
                0.6127,
                0.6154,
                0.5459,
                0.6225,
                0.6628,
                0.6577,
                0.6759,
                0.6846,
                0.7619,
                0.7769,
                0.7862,
                0.787
            ],
            "loss": [
                1.9783153926849366,
                1.6614973188400268,
                1.4288337879180908,
                1.3737384340286254,
                1.4145935908317566,
                1.1660198001861573,
                1.2000448033332825,
                1.2449983192443848,
                1.073088078546524,
                0.9737061535835266,
                1.105888773059845,
                0.9595423048496247,
                0.915560595703125,
                0.9004857444286346,
                0.8304849479258061,
                0.8811012368679046,
                0.7132569316864014,
                0.6326236196994781,
                0.5805146109968424,
                0.5947687090873718
            ]
        },
        "label": {
            "accuracy": [
                0.278,
                0.4152,
                0.4617,
                0.4871,
                0.4442,
                0.5866,
                0.5665,
                0.5625,
                0.6127,
                0.6154,
                0.5459,
                0.6225,
                0.6628,
                0.6577,
                0.6759,
                0.6846,
                0.7619,
                0.7769,
                0.7862,
                0.787
            ],
            "hits_at_k": [
                0.4633,
                0.6242,
                0.7382,
                0.7593,
                0.7475,
                0.8239,
                0.8022,
                0.8043,
                0.8495,
                0.8722,
                0.8369,
                0.8796,
                0.887,
                0.8835,
                0.8908,
                0.8914,
                0.9592,
                0.9753,
                0.986,
                0.9852
            ],
            "loss": [
                1.9783153926849366,
                1.6614973188400268,
                1.4288337879180908,
                1.3737384340286254,
                1.4145935908317566,
                1.1660198001861573,
                1.2000448033332825,
                1.2449983192443848,
                1.073088078546524,
                0.9737061535835266,
                1.105888773059845,
                0.9595423048496247,
                0.915560595703125,
                0.9004857444286346,
                0.8304849479258061,
                0.8811012368679046,
                0.7132569316864014,
                0.6326236196994781,
                0.5805146109968424,
                0.5947687090873718
            ]
        }
    },
    "train": {
        "combined": {
            "accuracy": [
                0.2758333333333333,
                0.41158333333333336,
                0.4599,
                0.4925,
                0.44125,
                0.5783833333333334,
                0.56185,
                0.5615833333333333,
                0.6117,
                0.6155,
                0.5474,
                0.6191666666666666,
                0.6612166666666667,
                0.6563833333333333,
                0.6745166666666667,
                0.6847333333333333,
                0.7557666666666667,
                0.7726833333333334,
                0.7827166666666666,
                0.7859333333333334
            ],
            "loss": [
                1.9837756731669107,
                1.6693969327290852,
                1.4293828234354655,
                1.3736332539876301,
                1.4210530075073242,
                1.1800180877685547,
                1.2036098621368407,
                1.245868607711792,
                1.0780691647847493,
                0.9756261206309,
                1.1070945477803549,
                0.9680410415649414,
                0.905208904393514,
                0.9056149331410726,
                0.8291425329844156,
                0.8703993370056152,
                0.706636447652181,
                0.6432052667617798,
                0.5890168155034383,
                0.6048753837585449
            ]
        },
        "label": {
            "accuracy": [
                0.2758333333333333,
                0.41158333333333336,
                0.4599,
                0.4925,
                0.44125,
                0.5783833333333334,
                0.56185,
                0.5615833333333333,
                0.6117,
                0.6155,
                0.5474,
                0.6191666666666666,
                0.6612166666666667,
                0.6563833333333333,
                0.6745166666666667,
                0.6847333333333333,
                0.7557666666666667,
                0.7726833333333334,
                0.7827166666666666,
                0.7859333333333334
            ],
            "hits_at_k": [
                0.4686,
                0.61645,
                0.7322666666666666,
                0.7529833333333333,
                0.7413666666666666,
                0.81755,
                0.7958666666666666,
                0.7995,
                0.8461833333333333,
                0.8689166666666667,
                0.8322333333333334,
                0.87705,
                0.8858166666666667,
                0.88105,
                0.89115,
                0.8914166666666666,
                0.95685,
                0.9722166666666666,
                0.98525,
                0.9834166666666667
            ],
            "loss": [
                1.9837756731669107,
                1.6693969327290852,
                1.4293828234354655,
                1.3736332539876301,
                1.4210530075073242,
                1.1800180877685547,
                1.2036098621368407,
                1.245868607711792,
                1.0780691647847493,
                0.9756261206309,
                1.1070945477803549,
                0.9680410415649414,
                0.905208904393514,
                0.9056149331410726,
                0.8291425329844156,
                0.8703993370056152,
                0.706636447652181,
                0.6432052667617798,
                0.5890168155034383,
                0.6048753837585449
            ]
        }
    },
    "validation": {
        "combined": {
            "accuracy": [],
            "loss": []
        },
        "label": {
            "accuracy": [],
            "hits_at_k": [],
            "loss": []
        }
    }
}
```

**Comment by w4nderlust** [comment]
Added a further fix commit and tested with your specific output confirming it works.

**Comment by sliecer** [comment]
I can confirm that it's working now. Thanks very much 👍
